### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by mn113** [LeaVerou/multirange#20]
I can't find any, on this repo or on https://leaverou.github.io/multirange/ .
Is there any??

**Comment by LeaVerou** [comment]
What kind of documentation are you looking for? It's a pretty tiny plugin, the way to use it is described in https://leaverou.github.io/multirange/
You just include it, and then you can use 2-handle sliders by using HTML like `<input type="range" multiple value="10,80" />`. This used to be in the HTML5 spec, but was dropped due to lack of implementations…
